FROM python:3.8.13
RUN mkdir -p /opt/project-dummy
WORKDIR  /opt/project-dummy
ADD requirements.txt .
RUN pip install -U pip  \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple  \
    && pip install -r requirements.txt \
